apiVersion: v1
kind: ConfigMap
metadata:
  name: rpmdm-auth-properties
  namespace: {{ .Values.namespace }}
data:
  mdm_authentication_service.properties: |
    authentication.active_dir.url={{ .Values.ldap.active_dir_url }}
    authentication.active_dir.domain={{ .Values.ldap.active_dir_domain }}
    authentication.host=localhost
    authentication.port=9901
    user.host=rp-mdm-user
    user.port=443
    permission.host=rp-mdm-perm
    permission.port=443
    trace_messages=false
