apiVersion: v1
kind: ConfigMap
metadata:
  name: rpmdm-core-properties
  namespace: {{ .Values.namespace }}
data:
  redpointmdm.properties: |
    rpmdm.service.host=0.0.0.0
    rpmdm.service.port=9902
    rpmdm.authentication.url=http://rp-mdm-auth:443/mdm
    rpmdm.usergroup.url=http://rp-mdm-user:443/mdm
    rpmdm.permission.url=http://rp-mdm-perm:443/mdm
    rpmdm.service.logging=true
