apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  labels:
    app: redpoint-mdm
  name: mdm-aad-pod-identity
  namespace: {{ .Values.namespace }}
spec:
  clientID: c36d335b-5736-4f26-a6a1-5e1058cc2316
  resourceID: /subscriptions/0d028bf4-2995-4b16-a4e4-4360adf6a0ed/resourcegroups/rg-poccore-aks-infra/providers/Microsoft.ManagedIdentity/userAssignedIdentities/mdm-aad-pod-identity
  type: 0
